### PR TITLE
feat(#1): setup a basic health check and added a gitignore file

### LINKED ISSUE #1: Add basic endpoint
Would be good to have an endpoint such as a healtcheck or a GET for now such /healthcheck

### PR DESCRIPTION
**Pull request by sidalidev**
@neelp1 this should resolve #1, let me know if it okay 😊

### CODE REVIEW

**Comment by neelp1** [comment]
Thanks for the pull request. I tried `curl http://localhost:3000/healthcheck` but got `Cannot GET /healthcheck`. Am I doing something wrong?

**Comment by neelp1** [comment]
Hello

I think you may have replied to the wrong person. :P

But I have added a comment to
https://github.com/neelp1/skeleton-node-app/pull/2. Please have a look.

Thanks you.

**Comment by sidalidev** [comment]
@neelp1  thats weido... 🧐
oct-15-2018 09-17-34

**Comment by neelp1** [comment]
It works if I spin up the docker container :) my node on the computer must be out of date or something.

**Pull request merged**
